# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Jonghun Daniel Lee
title: MD
email: jonghun.d.lee@gmail.com
#phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: https://www.instagram.com/supd_/
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /assets/image/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  2018.04 ~ 	   바바그룹 힙합퍼 / 스토어팀 MD/대리 
  
  - 스토어 운영 및 영업 계획 수립


  2015.11 ~ 2017.12  ㈜스타일쉐어 / 커머스팀 MD 
  
  - SNS기반 모바일 커머스 런칭 멤버


  2014.08 ~ 2015.09  AWEHEAD / 사원 
  
  - Web,App 신규 플랫폼 기획 및 운영


  2005.03 ~ 2013.02  한성대학교 – 영어영문학

    - 패션, 잡화 등 카테고리 상품기획 온라인 MD 실무 경력
    - 홀세일 비즈니스 플래닝 및 판매, 각종 채널을 이용한 상품 판매 운영 경험
    - e커머스 사업 기획, 영업, 매출 신장 전략 수립 및 관리
    - 다양한 브랜드들과의 협업 경험
    - 신규 사이트, 어플리케이션 UI, UX 구축 및 리뉴얼 기획 경험


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  [준비된 러너(learner)]

  새로이 경험하는 것에 적극적이고 배움에 두려움이 없습니다.

  온라인 커머스 비즈니스를 접하며 동료 개발자들의 작업에 관심을 갖고 직접 배우고자 하였습니다. 이를 위해 친분이 있는 개발자에게 개인적으로 프로그래밍에 관한 강습을 받기도 했습니다. 

  그로 인해 타당한 근거와 가능성을 기반으로 막연하지 않은, 현실적인 기능 개발을 요청할 수 있었습니다. 팀 간의 협업에서 서로의 업무에 대한 무지에서 나타날 수 있는 크고 작은 충돌이 저로 인해 생기지 않았으며, 보다 효과적인 기능 구현이 가능하였습니다.

  업무 뿐 아니라 개인의 성장에 도움이 될 것이라 생각하는 부분에 있어서 항상 배우는 자세를 갖추고 있으며, 빠른 습득 능력으로 실제 업무에 효과적으로 응용합니다.
  
  
  [전세계 시장을 개척하는 패션매니아]

  MD가 아닌 소비자로서 저는 쇼핑 스페셜리스트라고 스스로 감히 말할 수 있습니다.

  ‘멋’이라는 것에 대한 갈망으로 저는 누구보다 다양한 구매 경험을 겪었습니다.

  한정된 수량 혹은 제한적으로 발매하는 값어치 있는 제품을 구하기 위해 여러 채널을 통해 정보를 얻고 구매를 시도하여 좋은 결과를 얻은 경험이 다수 있습니다. 이는 수많은 노력이 뒷받침 되었기 때문이라고 생각합니다. 

  발매 정보를 얻기 위해 국내외 커뮤니티와 SNS 채널을 모니터링하고, 구매 방법에 대한 분석 그리고 그를 위해 가장 효과적인 옵션을 생각합니다.

  온라인 구매는 비교적 쉬운 편이었으나, 기억에 남는 남다른 경험을 꼽자면 피치 못할 사정으로 런칭 시기를 놓쳐 구하지 못한 신발을 노력하여 가까스로 구매한 일이 있습니다.

  너무 갖고 싶었던 신발이기에 온라인 몰을 여럿 알아보다가 상대적으로 그에 대한 수요가 적은 동유럽 국가의 한 매장에서 스탁을 확인했습니다. 마침 SNS를 통해 지인이 그 근방에 방문중이라는 알게 되었고 미리 양해를 구하고 도움을 요청했습니다.
  
  승낙 이후, 인터넷 전화 스카이프로 동유럽의 상점에 전화를 해, 영어회화가 가능한 직원과 긴 대화 끝에 스토어 픽업할 것을 약속하고 마지막 남은 제품을 홀드할 수 있었습니다. 지인에게 요청하여 그의 일정과 루트에 맞추어 상품을 픽업하고 신발을 손에 넣었습니다.

  남다른 열정과 다양한 구매 경험을 기반으로 소비자의 패턴을 다각도로 분석할 수 있습니다. 보다 나은 서비스를 제공하기 위하여 더 많이 경험하고 실무에 응용할 것입니다.
  
  
  [분석과 직관을 거쳐 고객만족으로]
  
  시장을 면밀히 분석하여 다양한 고객경험을 제공하고 싶습니다.

  저는 스타일쉐어 재직시절 MD로서 업체 관리, 판매상품 소싱 뿐만 아니라, 런칭 초기 미완의 형태였던 스토어 디자인과 기능의 발전을 위한 아이디어 회의에 참여하여 많은 의견을 제시하였습니다. 

  SNS를 기반으로 한 온라인 커머스인 스타일쉐어는 SNS 채널 유저들의 포스팅을 곧 상품에 대한 후기로 사용할 수 있습니다. 따라서 상품과 후기의 연결을 얼마나 많이 생성하고 어떻게 보여주는지가 매출에 크게 영향을 주었습니다. 

  무분별한 저 퀄리티의 후기는 아무리 많다 하더라도 상품에 긍정적 영향을 끼치지 않았습니다. 양질의 후기를 확보하기 위해, 좋은 후기를 생성하고 있던 인기 유저들을 모아 서포터즈 운영을 하였습니다. 목적성을 지니고 만들어진 양질의 후기들은 홍보의 수단임과 동시에 유저들에게 도움이 되는 좋은 게시물이 될 수 있습니다.
  
  서포터즈 운영을 통해 SNS채널의 질적인 향상과 커머스 매출 증대라는 두 마리 토끼를 모두 잡았습니다.

  저는 서비스의 특징을 정확히 이해하고, 그 안에서 새로운 수단을 생각해내어 곧 긍정적인 고객 경험으로 이어지게 할 수 있습니다.
  

  취미 및 특기

  - 여행, 바이올린 연주


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
